# Generated by Django 3.2.18 on 2023-03-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('publication_date_and_time', models.DateTimeField(auto_now_add=True)),
                ('is_checked_by_staff', models.BooleanField(default=False)),
            ],
        ),
    ]
