# Generated by Django 3.2.18 on 2023-03-10 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import server.api_data.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('city', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('website', models.URLField(validators=[server.api_data.validators.OptionalSchemeURLValidator])),
                ('image', models.ImageField(upload_to='places')),
                ('cost_free', models.BooleanField(default=False)),
                ('fear_water', models.BooleanField(default=False)),
                ('fear_height', models.BooleanField(default=False)),
                ('fear_animals', models.BooleanField(default=False)),
                ('fear_other', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('longitude', 'latitude')},
            },
        ),
    ]
