# Generated by Django 3.2.18 on 2023-03-14 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='places',
            old_name='name',
            new_name='title',
        ),
    ]
