# Generated by Django 3.2.18 on 2023-03-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_data', '0003_auto_20230329_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
