# Generated by Django 3.2.18 on 2023-03-31 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_data', '0004_alter_places_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
