version: '3.9'

services:
  app:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/fear
    ports:
      - 8000:8000
    image: app:fear_backend
    container_name: fear_local
    env_file:
      - ./server/envs/.env
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres-user
      POSTGRES_DB: fear_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data

