version: '3.9'

services:
  app:
    build:
      context: .
    command: gunicorn server.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/fear
      - ./staticfiles:/fear/staticfiles
    ports:
      - 8000:8000
    image: tsveti1103/fear
    container_name: fear_server
    env_file:
      - ./server/envs/.env.prod
    depends_on:
      - postgres:15.2
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres-user
      POSTGRES_DB: fear_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  nginx:
    image: nginx
    ports:
      - 81:80
      - 443:443
    volumes:
      - ./staticfiles:/home/app/web/staticfiles
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - app
